/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-08-11 00:15:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board3;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class read_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/board3/../common/easyui_common.jsp", Long.valueOf(1659485655057L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("  \r\n");

	String rb_title = null;
	String rb_writer = null;
	String rb_content = null;
	String rb_date = null;
	String rb_group = null;
	String rb_pos = null;
	String rb_step = null;
	String rb_no = null;
	String rb_pw = null;
	
	List<Map<String,Object>> boardList = 
			(List<Map<String,Object>>)request.getAttribute("boardList");
	if(boardList !=null && boardList.size()>0){
		rb_title = boardList.get(0).get("B_TITLE").toString();
		rb_writer = boardList.get(0).get("B_WRITER").toString();
		rb_content = boardList.get(0).get("B_CONTENT").toString();
		rb_date = boardList.get(0).get("B_DATE").toString();
		rb_group = boardList.get(0).get("B_GROUP").toString();
		rb_pos = boardList.get(0).get("B_POS").toString();
		rb_step = boardList.get(0).get("B_STEP").toString();
		rb_no = boardList.get(0).get("B_NO").toString();
		rb_pw = boardList.get(0).get("B_PW").toString();
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");

// íì¥ìë¥¼ jspë¡ í´ì¼ ì¤í¬ë¦½íë¦¿ ì¬ì©ì´ ê°ë¥í¨
// JSP = html+CSS+JS(ë¸ë¼ì°ì -ì¸í°íë¦¬í°-ë¡ì»¬-ë¤ì´ë¡ë)+JAVA (ë°±ìë-ìë²ê° ì£¼ì²´-ìë²ì¸¡ìì ì²ë¦¬ë ê²°ê³¼ê° ë¤ì´ë¡ëë¨)
// ì ì¤ìíë ì´ê²? > ìê°ì°¨ ëë¬¸ì! (ì¸ì¤í´ì¤í - ìì¹ - ì±ê¸í¤í¨í´ - ìë¸ë¦¿ ì±ê¸í¤ ê´ë¦¬)
// ìë¸ë¦¿ì ë¼ì´í ì¬ì´í´ - ì¤ë ëë¡ ê´ë¦¬ > ê´ë¦¬ëë ì£¼ì²´: ê°ì²´(ìë¸ë¦¿)
// ì ìë¸ë¦¿ì´ì´ì¼ íì§? >> ìë¸ë¦¿ì´ì´ì¼ ì¹ìë¹ì¤ê° ê°ë¥íëê»~
//		                       ì¹ìë¹ì¤ë ìì²­ì¼ë¡ ììí´ì ìëµì¼ë¡ ëëë ê² (ìì²­ì ìí´ ìì²­ê°ì²´ì ìëµê°ì²´ì ëí ê°ì²´ ì£¼ìì´ íìíë¤.)
//                                                                ëê°? í°ìº£ì´! ëêµ¬ìê²? ìì²­ììê²!
//		 												ìì²­ë°©ì: GET/POST
//		 												ìë¹ì¤ë¥¼ ì ê³µíë ë°±ìë ë¨ìì ì ì¡ë°©ìì ë§¤ì¹­ëë ë©ìëê° íìíë¤ (doGet, doPost)
// a.jsp -> a_jsp.java -> a_jsp.class -> ë¸ë¼ì°ì  ì°ê¸°
//     jsp ì»¨íì´ë(ìì§), servlet-api.jar(ìë¸ë¦¿ ìì§)
// init() - service() - destroy()  
// >> ê°ë°ìë? init() - service(req,res) / doGet,doPost(êµ¬ë¶ ê°ë¥) - destroy()
// í°ìº£ ìë²ê° init()ê³¼ destroy()ê¹ì§ë ì±ìì ì§ë¤ - ê°ë°ì ì±ìì´ ìë
// íë¡ì í¸ ì´ë¦ë§ë¤ ê²½ë¡ê° ë¤ë¥¼ ì ìë¤.
// ë§¤ë² ê·¸ ëë§ë¤ ê²½ë¡ë¥¼ ìì íë¤?? ì°ì©
// WASìì ê´ë¦¬íë server.xmlë¬¸ììì Contextì ì ë³´ë¥¼ ê°ì ¸ì¤ë ë©ìë í¸ì¶!
    StringBuilder path = new StringBuilder(request.getContextPath());
    path.append("/");

      out.write("   \r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.jeasyui.com/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path.toString() );
      out.write("themes/default/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path.toString() );
      out.write("demo/demo.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path.toString() );
      out.write("themes/icon.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js\"></script>");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("// html만으로 처리\r\n");
      out.write("// javascript만으로 처리\r\n");
      out.write("// html+javascript혼합 처리(권장=리액트)\r\n");
      out.write("	function boardList(){\r\n");
      out.write("		location.href=\"./boardList.pj\";\r\n");
      out.write("	}\r\n");
      out.write("	function dlgIns_save(){\r\n");
      out.write("		$(\"#f_boardIns\").submit();\r\n");
      out.write("	}\r\n");
      out.write("	function repleForm(){\r\n");
      out.write("		$(\"#dlg_boardIns\").dialog('open');\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function dlgUpd_save(){\r\n");
      out.write("		$(\"#f_boardUpd\").submit();\r\n");
      out.write("	}\r\n");
      out.write("	function updateForm(){\r\n");
      out.write("		$(\"#dlg_boardUpd\").dialog('open');\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function deleteForm(){\r\n");
      out.write("		// 리액트 계속 - import(ES6, module, ES6 기준문법-안전함, require-CommonJS)\r\n");
      out.write("		$(\"#dlg_boardDel\").dialog({\r\n");
      out.write("			title: '글삭제 - 비밀번호 확인',\r\n");
      out.write("			href: 'boardDelForm.jsp?b_no=");
      out.print(rb_no);
      out.write("&b_pw=");
      out.print(rb_pw);
      out.write("',\r\n");
      out.write("			modal: true,\r\n");
      out.write("			closed: true\r\n");
      out.write("		});\r\n");
      out.write("		$(\"#dlg_boardDel\").dialog('open');\r\n");
      out.write("	}\r\n");
      out.write("	function boardDel(){\r\n");
      out.write("		console.log(\"boardDel 호출성공\");\r\n");
      out.write("		// 자바스크립트에서는 값에 ''이나 \"\"을 안붙이면 변수로 처리됨\r\n");
      out.write("		let db_pw = \"");
      out.print(rb_pw);
      out.write("\";\r\n");
      out.write("		const u_pw = $(\"#u_pw\").textbox('getValue');\r\n");
      out.write("		if(u_pw == db_pw){\r\n");
      out.write("			$.messager.confirm('Confirm', '정말 삭제할거야?', function(r){\r\n");
      out.write("				if(r){\r\n");
      out.write("					location.href=\"./boardDelete.pj?b_no=\"+");
      out.print(rb_no);
      out.write("\r\n");
      out.write("				} \r\n");
      out.write("			});\r\n");
      out.write("		}else {\r\n");
      out.write("			alert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <table align=\"center\" id=\"p\" class=\"easyui-panel\" title=\"글상세보기\" data-options=\"footer:'#tb_read'\"\r\n");
      out.write("        style=\"width:670px;height:380px;padding:10px;background:#fafafa;\">\r\n");
      out.write("	    	<tr>\r\n");
      out.write("	    	<td>제목</td>\r\n");
      out.write("	    	<td><input id=\"b_title\" value=\"");
      out.print(rb_title);
      out.write("\" name=\"b_title\" data-options=\"width:'450px'\" class=\"easyui-textbox\"></td>\r\n");
      out.write("	    	</tr>\r\n");
      out.write("	    	<tr>\r\n");
      out.write("	    	<td>작성자</td>\r\n");
      out.write("	    	<td><input id=\"b_writer\" value=\"");
      out.print(rb_writer);
      out.write("\" name=\"b_writer\" class=\"easyui-textbox\"></td>\r\n");
      out.write("	    	</tr>\r\n");
      out.write("	    	<tr>\r\n");
      out.write("	    	<td>내용</td>\r\n");
      out.write("	    	<td><input id=\"b_content\" value=\"");
      out.print(rb_content);
      out.write("\" name=\"b_content\" data-options=\"multiline:'true', width:'570px', height:'90px'\" class=\"easyui-textbox\"></td>\r\n");
      out.write("	    	</tr>\r\n");
      out.write("	    	<tr>\r\n");
      out.write("	    	<td>작성일</td>\r\n");
      out.write("	    	<td><input id=\"b_date\" value=\"");
      out.print(rb_date);
      out.write("\" name=\"b_date\" class=\"easyui-textbox\"></td>\r\n");
      out.write("	    	</tr>	    	\r\n");
      out.write("	   </table>\r\n");
      out.write("	 <div id=\"tb_read\" style=\"padding:2px 5px;\" align=\"center\">\r\n");
      out.write("	    <a href=\"javascript:repleForm()\" class=\"easyui-linkbutton\" iconCls=\"icon-edit\" plain=\"true\">댓글쓰기</a>\r\n");
      out.write("	    <a href=\"javascript:updateForm()\" class=\"easyui-linkbutton\" iconCls=\"icon-add\" plain=\"true\">수정</a>\r\n");
      out.write("	    <a href=\"javascript:deleteForm()\" class=\"easyui-linkbutton\" iconCls=\"icon-remove\" plain=\"true\">삭제</a>\r\n");
      out.write("	    <a href=\"javascript:boardList()\" class=\"easyui-linkbutton\" iconCls=\"icon-search\" plain=\"true\">목록</a>\r\n");
      out.write("	</div>	\r\n");
      out.write("	\r\n");
      out.write("<!-- 글 삭제 시작 -->	\r\n");
      out.write("	<div id=\"dlg_boardDel\" footer=\"#btn_boardDel\" class=\"easyui-dialog\" title=\"삭제하기\" data-options=\"modal:true,closed:true\" style=\"width:300px;height:200px;padding:10px\">\r\n");
      out.write("		<div id=\"btn_boardDel\" align=\"right\">\r\n");
      out.write("			<a href=\"javascript:boardDel()\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\">확인</a>\r\n");
      out.write("			<a href=\"javascript:boardDelClose()\" class=\"easyui-linkbutton\" iconCls=\"icon-clear\">닫기</a>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("<!-- 글 삭제 끝 -->\r\n");
      out.write("	\r\n");
      out.write("<!-- 수정 화면 추가 시작 -->\r\n");
      out.write("    <div id=\"dlg_boardUpd\" footer=\"#tb_boardUpd\" class=\"easyui-dialog\" title=\"수정하기\" data-options=\"modal:true,closed:true\" style=\"width:600px;height:400px;padding:10px\">\r\n");
      out.write("        <!-- 바이너리(문자열+숫자) 파일을 전송할 때는 반드시 post방식 처리 첨부파일 처리 시 -->\r\n");
      out.write("        <!-- base2, base8, base16, base64 텍스트 파일(문자열치환-파일크기가 커진다) -->\r\n");
      out.write("        <!-- <form id=\"f_boardIns\" method=\"post\" enctype=\"multipart/form-data\" action=\"./boardInsert.pj\"> -->\r\n");
      out.write("        <form id=\"f_boardUpd\" method=\"get\" action=\"./boardUpdate.pj\">\r\n");
      out.write("        <!-- 태그안에 자바변수 사용가능한가? 가능함 -->\r\n");
      out.write("	    <input type=\"hidden\" id=\"b_no\" name=\"b_no\" value=\"");
      out.print(rb_no);
      out.write("\">\r\n");
      out.write("        	<table>\r\n");
      out.write("        		<tr>\r\n");
      out.write("        			<td width=\"100px\">제&nbsp;&nbsp;&nbsp;목</td>\r\n");
      out.write("        			<td width=\"500px\"><input id=\"b_title\" value=\"");
      out.print(rb_title );
      out.write("\" name=\"b_title\" class=\"easyui-textbox\" data-options=\"width:'250px'\" required></td>\r\n");
      out.write("        		</tr>\r\n");
      out.write("        		<tr>\r\n");
      out.write("        			<td width=\"100px\">작&nbsp;성&nbsp;자</td>\r\n");
      out.write("        			<td width=\"500px\"><input id=\"b_writer\" value=\"");
      out.print(rb_writer );
      out.write("\" name=\"b_writer\" class=\"easyui-textbox\" data-options=\"width:'150px'\" required></td>\r\n");
      out.write("        		</tr>\r\n");
      out.write("        		<tr>\r\n");
      out.write("        			<td width=\"100px\">내&nbsp;&nbsp;&nbsp;용</td>\r\n");
      out.write("        			<td width=\"500px\"><input id=\"b_content\" value=\"");
      out.print(rb_content );
      out.write("\" name=\"b_content\" class=\"easyui-textbox\" data-options=\"multiline:'true',width:'350px', height:'90px'\" required></td>\r\n");
      out.write("        		</tr>\r\n");
      out.write("        	</table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("        <!-- 다이얼로그 화면 버튼 추가 시작 -->\r\n");
      out.write("	<div id=\"tb_boardUpd\">\r\n");
      out.write("	<a href=\"javascript:dlgUpd_save()\" class=\"easyui-linkbutton\">저장</a>\r\n");
      out.write("	<a href=\"javascript:dlgUpd_close()\" class=\"easyui-linkbutton\">닫기</a>\r\n");
      out.write("	</div>    \r\n");
      out.write("    <!-- 다이얼로그 화면 버튼 추가  끝   -->\r\n");
      out.write("<!-- 수정 화면 추가  끝   -->	\r\n");
      out.write("	\r\n");
      out.write("<!-- 댓글입력 화면 추가 시작 -->\r\n");
      out.write("    <div id=\"dlg_boardIns\" footer=\"#tb_boardIns\" class=\"easyui-dialog\" title=\"댓글쓰기\" data-options=\"modal:true,closed:true\" style=\"width:600px;height:400px;padding:10px\">\r\n");
      out.write("<!-- 		바이너리 (문자열+숫자) 파일을 전송할 때는 반드시 post 방식으로 처리한다 -->\r\n");
      out.write("<!-- 		base2, base8, base16, base64 텍스트파일 (문자열 치환-파일 크기가 커진다) -->\r\n");
      out.write("<!--        <form id=\"f_boardIns\" method=\"post\" enctype=\"multipart/form-data\" action=\"./boardInsert.pj\"> -->\r\n");
      out.write("        <form id=\"f_boardIns\" method=\"get\" action=\"./boardInsert.pj\">\r\n");
      out.write("        <!-- 태그 안에 자바 변수 사용 가능한가? > 가능함 -->\r\n");
      out.write("	    <input type=\"hidden\" id=\"b_group\" name=\"b_group\" value=\"");
      out.print(rb_group);
      out.write("\">\r\n");
      out.write("	    <input type=\"hidden\" id=\"b_pos\" name=\"b_pos\" value=\"");
      out.print(rb_pos);
      out.write("\">\r\n");
      out.write("	    <input type=\"hidden\" id=\"b_step\" name=\"b_step\" value=\"");
      out.print(rb_step);
      out.write("\">\r\n");
      out.write("        	<table>\r\n");
      out.write("        		<tr>\r\n");
      out.write("        			<td width=\"100px\">제&nbsp;&nbsp;&nbsp;목</td>\r\n");
      out.write("        			<td width=\"500px\"><input id=\"b_title\" name=\"b_title\" class=\"easyui-textbox\" data-options=\"width:'250px'\" required></td>\r\n");
      out.write("        		</tr>\r\n");
      out.write("        		<tr>\r\n");
      out.write("        			<td width=\"100px\">작&nbsp;성&nbsp;자</td>\r\n");
      out.write("        			<td width=\"500px\"><input id=\"b_writer\" name=\"b_writer\" class=\"easyui-textbox\" data-options=\"width:'150px'\" required></td>\r\n");
      out.write("        		</tr>\r\n");
      out.write("        		<tr>\r\n");
      out.write("        			<td width=\"100px\">내&nbsp;&nbsp;&nbsp;용</td>\r\n");
      out.write("        			<td width=\"500px\"><input id=\"b_content\" name=\"b_content\" class=\"easyui-textbox\" data-options=\"multiline:'true',width:'350px', height:'90px'\" required></td>\r\n");
      out.write("        		</tr>\r\n");
      out.write("        		<tr>\r\n");
      out.write("        			<td width=\"100px\">비&nbsp;&nbsp;&nbsp;번</td>\r\n");
      out.write("        			<td width=\"500px\"><input id=\"b_pw\" name=\"b_pw\" class=\"easyui-textbox\" data-options=\"width:'100px'\" required></td>\r\n");
      out.write("        		</tr>\r\n");
      out.write("        		<tr>\r\n");
      out.write("        			<td width=\"100px\">첨부파일</td>\r\n");
      out.write("        			<td width=\"500px\"><input id=\"bs_file\" name=\"bs_file\" class=\"easyui-filebox\" data-options=\"width:'350px'\"></td>\r\n");
      out.write("        		</tr>\r\n");
      out.write("        	</table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("        <!-- 다이얼로그 화면 버튼 추가 시작 -->\r\n");
      out.write("	<div id=\"tb_boardIns\">\r\n");
      out.write("	<a href=\"javascript:dlgIns_save()\" class=\"easyui-linkbutton\">저장</a>\r\n");
      out.write("	<a href=\"javascript:dlgIns_close()\" class=\"easyui-linkbutton\">닫기</a>\r\n");
      out.write("	</div>    \r\n");
      out.write("    <!-- 다이얼로그 화면 버튼 추가  끝   -->\r\n");
      out.write("<!-- 댓글입력 화면 추가  끝   -->	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
